name: Frontend CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: npm

      - name: Install Dependencies and Build Frontend
        run: |
          npm install
          npm run build

      - name: Build Frontend Docker Image
        run: docker build . --file ./Dockerfile --tag ghcr.io/${{ github.repository_owner }}/frontend:latest

      - name: Log in to GHCR
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Frontend Docker Image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/frontend:latest
